/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_stefanji_playground_TestJNIRegiester */

#ifndef _Included_io_github_stefanji_playground_TestJNIRegiester
#define _Included_io_github_stefanji_playground_TestJNIRegiester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_stefanji_playground_TestJNIRegiester
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_stefanji_playground_TestJNIRegiester_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
